name=SegLCDLib
architectures=*
version=0.0.2-SNAPSHOT
author=Petr Kracik
maintainer=Petr Kracik <petrkr@petrkr.net>
sentence=Library for segment LCD displays.
paragraph=Currently supports HT1621, HT1622, VK0192, PCF85176 and PCF8576 controllers, with display drivers and mappings for supported modules and room to extend support for additional displays.
category=Display
url=https://github.com/petrkr/SegLCDLib
